<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.aisino.com" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="baseWebService" targetNamespace="http://ws.aisino.com">
    <script/>
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ws.aisino.com" elementFormDefault="unqualified" targetNamespace="http://ws.aisino.com" version="1.0">
            <xs:element name="eiInterface" type="tns:eiInterface"/>
            <xs:element name="eiInterfaceResponse" type="tns:eiInterfaceResponse"/>
            <xs:complexType name="eiInterface">
                <xs:sequence>
                    <xs:element form="qualified" minOccurs="0" name="in0" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="eiInterfaceResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="eiInterfaceResponse">
        <wsdl:part element="tns:eiInterfaceResponse" name="parameters"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="eiInterface">
        <wsdl:part element="tns:eiInterface" name="parameters"> </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="BaseWebService">
        <wsdl:operation name="eiInterface">
            <wsdl:input message="tns:eiInterface" name="eiInterface"> </wsdl:input>
            <wsdl:output message="tns:eiInterfaceResponse" name="eiInterfaceResponse"> </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="baseWebServiceSoapBinding" type="tns:BaseWebService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="eiInterface">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="eiInterface">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="eiInterfaceResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="baseWebService">
        <wsdl:port binding="tns:baseWebServiceSoapBinding" name="baseWebServicePort">
            <soap:address location="http://hsy365.com/mall/api/ws/invoice"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>